using System.ComponentModel;
using AwesomeAssertions;

namespace TitanFx.PropertyChanged.Tests;

public static class FunctionalityTests
{
    [Fact]
    public static void AutoGeneratedPropertiesShouldOnlyNotifyWhenTheValueChanges()
    {
        // arrange
        var sut = new TestReactive();
        var eventArgs = new List<(object?, EventArgs, string?)>();
        sut.PropertyChanging += (s, e) => eventArgs.Add((s, e, sut.Value));
        sut.PropertyChanged += (s, e) => eventArgs.Add((s, e, sut.Value));

        // act
        sut.Value = "abc";
        sut.Value = "abc";
        sut.Value = "def";
        sut.Value = null;
        sut.Value = null;
        sut.Value = "";
        sut.Value = "";
        sut.Value = "";

        // assert
        _ = eventArgs
            .Should()
            .BeEquivalentTo(
                new (object?, EventArgs, string?)[]
                {
                    (sut, new PropertyChangingEventArgs("Value"), null),
                    (sut, new PropertyChangedEventArgs("Value"), "abc"),
                    (sut, new PropertyChangingEventArgs("Value"), "abc"),
                    (sut, new PropertyChangedEventArgs("Value"), "def"),
                    (sut, new PropertyChangingEventArgs("Value"), "def"),
                    (sut, new PropertyChangedEventArgs("Value"), null),
                    (sut, new PropertyChangingEventArgs("Value"), null),
                    (sut, new PropertyChangedEventArgs("Value"), ""),
                }
            );
    }

    [Fact]
    public static void AutoGeneratedPropertiesShouldWorkWithRefStructs()
    {
        // arrange
        var sut = new RefStructTest();
        var eventArgs = new List<(object?, EventArgs)>();
        sut.PropertyChanging += (s, e) => eventArgs.Add((s, e));
        sut.PropertyChanged += (s, e) => eventArgs.Add((s, e));

        // act
        sut.Name = "abc";
        sut.Name = "abc";
        sut.Name = "def";
        sut.Name = null;
        sut.Name = null;
        sut.Name = "";
        sut.Name = "";
        sut.Name = "";

        // assert
        _ = eventArgs
            .Should()
            .BeEquivalentTo(
                new (object?, EventArgs)[]
                {
                    (null, new PropertyChangingEventArgs("Name")),
                    (null, new PropertyChangedEventArgs("Name")),
                    (null, new PropertyChangingEventArgs("Name")),
                    (null, new PropertyChangedEventArgs("Name")),
                    (null, new PropertyChangingEventArgs("Name")),
                    (null, new PropertyChangedEventArgs("Name")),
                    (null, new PropertyChangingEventArgs("Name")),
                    (null, new PropertyChangedEventArgs("Name")),
                }
            );
    }
}

[NotifyPropertyChanged, NotifyPropertyChanging]
internal sealed partial class TestReactive
{
    public partial string? Value { get; set; }
}
